#An example of a Secret structure. The actual values are created using the `kubectl create secret` command;
#this file is merely a reference template and does not contain actual data.
apiVersion: v1
kind: Secret
metadata:
  name: task-service-secrets
type: Opaque
stringData:
  JWT_SECRET: "<your-jwt-secret>"
  PASSWORD_POSTGRES: "<your-db-password>"
  URL_POSTGRES: "jdbc:postgresql://<your-rds-endpoint>:5432/taskservicedb"
  USERNAME_POSTGRES: "<your-db-username>"

---
apiVersion: v1
kind: Secret
metadata:
  name: user-service-secrets
type: Opaque
stringData:
  JWT_SECRET: "<your-jwt-secret>"
  JWT_EXPIRATION: "<jwt-expiration-in-ms>"
  PASSWORD_POSTGRES: "<your-db-password>"
  URL_POSTGRES: "jdbc:postgresql://<your-rds-endpoint>:5432/userservicedb"
  USERNAME_POSTGRES: "<your-db-username>"